version: '3'
services:
  rca-api-service:
    container_name: 'rca-api-service'
    env_file:
     - ./../../.env
    build:
      context: ./../../.
      dockerfile: ./docker/Dockerfile.dev
      args:
        bamboo_NPM_AUTH_TOKEN: 9ad2eb96-ff24-4df8-9f25-2a9120b121b6
        NODE_ENV: development
    volumes:
      - yarn:/usr/local/share/.cache/yarn/v4
      - ./../../src:/usr/app/src
      - ./../../test:/usr/app/test
      - ./../../typings:/usr/app/typings
      - ./../../.gitignore:/usr/app/.gitignore
      - ./../../.prettierrc:/usr/app/.prettierrc
      - ./../../jest.config.js:/usr/app/jest.config.js
      - ./../../package.json:/usr/app/package.json
      - ./../../tsconfig.json:/usr/app/tsconfig.json
      - ./../../tslint.json:/usr/app/tslint.json
      - ./../../yarn.lock:/usr/app/yarn.lock
      - ~/.bash_history:/root/.bash_history
    ports:
      - "${API_PORT}:${API_PORT}"
  
volumes:
  yarn: