export const officePropertyTypes = [
  {
    __raw_property_type__: {
      PTSMenu_id: 96,
      Type1_id: 6,
      Type1_tx: 'Office',
      Type1Full_tx: 'Office',
      Type1Abbreviated_tx: 'Office',
      Type1_cd: 'OFF',
      Type1Order_nb: 1,
      Type1Priority_nb: 2,
      Type1SourceTable_tx: 'propertytype',
      Type2_id: null,
      Type2_tx: null,
      Type2Full_tx: null,
      Type2Order_nb: null,
      Type2Priority_nb: 6,
      Type2SourceTable_tx: null,
      Type3_id: null,
      Type3_tx: null,
      Type3Full_tx: null,
      Type3Order_nb: null,
      Type3Priority_nb: 2,
      Type3SourceTable_tx: null,
      SyntheticId_tx: '6|propertytype||||',
    },
    id: '96',
    label: 'Office',
    slug: 'office-96',
    subPropertyTypes: [
      {
        parentId: '96',
        __raw_property_type__: {
          PTSMenu_id: 102,
          Type1_id: 6,
          Type1_tx: 'Office',
          Type1Full_tx: 'Office',
          Type1Abbreviated_tx: 'Office',
          Type1_cd: 'OFF',
          Type1Order_nb: 1,
          Type1Priority_nb: 2,
          Type1SourceTable_tx: 'propertytype',
          Type2_id: 7,
          Type2_tx: 'Office - CBD',
          Type2Full_tx: 'Office - CBD',
          Type2Order_nb: 1,
          Type2Priority_nb: 5,
          Type2SourceTable_tx: 'propertysubtype',
          Type3_id: null,
          Type3_tx: null,
          Type3Full_tx: null,
          Type3Order_nb: null,
          Type3Priority_nb: 2,
          Type3SourceTable_tx: null,
          SyntheticId_tx: '6|propertytype|7|propertysubtype||',
        },
        id: '102',
        label: 'Office - CBD',
        slug: 'office-cbd-102',
        subPropertyTypes: [],
        featureTypes: [
          {
            parentId: '102',
            __raw_property_type__: {
              PTSMenu_id: 103,
              Type1_id: 6,
              Type1_tx: 'Office',
              Type1Full_tx: 'Office',
              Type1Abbreviated_tx: 'Office',
              Type1_cd: 'OFF',
              Type1Order_nb: 1,
              Type1Priority_nb: 2,
              Type1SourceTable_tx: 'propertytype',
              Type2_id: 7,
              Type2_tx: 'Office - CBD',
              Type2Full_tx: 'Office - CBD',
              Type2Order_nb: 1,
              Type2Priority_nb: 5,
              Type2SourceTable_tx: 'propertysubtype',
              Type3_id: 26,
              Type3_tx: 'Medical',
              Type3Full_tx: 'Medical',
              Type3Order_nb: 2,
              Type3Priority_nb: 1,
              Type3SourceTable_tx: 'feature',
              SyntheticId_tx: '6|propertytype|7|propertysubtype|26|feature',
            },
            id: '103',
            label: 'Medical',
            slug: 'medical-103',
          },
          {
            parentId: '102',
            __raw_property_type__: {
              PTSMenu_id: 104,
              Type1_id: 6,
              Type1_tx: 'Office',
              Type1Full_tx: 'Office',
              Type1Abbreviated_tx: 'Office',
              Type1_cd: 'OFF',
              Type1Order_nb: 1,
              Type1Priority_nb: 2,
              Type1SourceTable_tx: 'propertytype',
              Type2_id: 7,
              Type2_tx: 'Office - CBD',
              Type2Full_tx: 'Office - CBD',
              Type2Order_nb: 1,
              Type2Priority_nb: 5,
              Type2SourceTable_tx: 'propertysubtype',
              Type3_id: 40,
              Type3_tx: 'R&D',
              Type3Full_tx: 'R&D',
              Type3Order_nb: 3,
              Type3Priority_nb: 1,
              Type3SourceTable_tx: 'feature',
              SyntheticId_tx: '6|propertytype|7|propertysubtype|40|feature',
            },
            id: '104',
            label: 'R&D',
            slug: 'r-d-104',
          },
          {
            parentId: '102',
            __raw_property_type__: {
              PTSMenu_id: 106,
              Type1_id: 6,
              Type1_tx: 'Office',
              Type1Full_tx: 'Office',
              Type1Abbreviated_tx: 'Office',
              Type1_cd: 'OFF',
              Type1Order_nb: 1,
              Type1Priority_nb: 2,
              Type1SourceTable_tx: 'propertytype',
              Type2_id: 7,
              Type2_tx: 'Office - CBD',
              Type2Full_tx: 'Office - CBD',
              Type2Order_nb: 1,
              Type2Priority_nb: 5,
              Type2SourceTable_tx: 'propertysubtype',
              Type3_id: 51,
              Type3_tx: 'Tech/Telecom/Data Center',
              Type3Full_tx: 'Tech/Telecom/Data',
              Type3Order_nb: 4,
              Type3Priority_nb: 1,
              Type3SourceTable_tx: 'feature',
              SyntheticId_tx: '6|propertytype|7|propertysubtype|51|feature',
            },
            id: '106',
            label: 'Tech/Telecom/Data',
            slug: 'tech-telecom-data-106',
          },
        ],
      },
      {
        parentId: '96',
        __raw_property_type__: {
          PTSMenu_id: 107,
          Type1_id: 6,
          Type1_tx: 'Office',
          Type1Full_tx: 'Office',
          Type1Abbreviated_tx: 'Office',
          Type1_cd: 'OFF',
          Type1Order_nb: 1,
          Type1Priority_nb: 2,
          Type1SourceTable_tx: 'propertytype',
          Type2_id: 8,
          Type2_tx: 'Office - Sub',
          Type2Full_tx: 'Office - Sub',
          Type2Order_nb: 2,
          Type2Priority_nb: 5,
          Type2SourceTable_tx: 'propertysubtype',
          Type3_id: null,
          Type3_tx: null,
          Type3Full_tx: null,
          Type3Order_nb: null,
          Type3Priority_nb: 2,
          Type3SourceTable_tx: null,
          SyntheticId_tx: '6|propertytype|8|propertysubtype||',
        },
        id: '107',
        label: 'Office - Sub',
        slug: 'office-sub-107',
        subPropertyTypes: [],
        featureTypes: [
          {
            parentId: '107',
            __raw_property_type__: {
              PTSMenu_id: 108,
              Type1_id: 6,
              Type1_tx: 'Office',
              Type1Full_tx: 'Office',
              Type1Abbreviated_tx: 'Office',
              Type1_cd: 'OFF',
              Type1Order_nb: 1,
              Type1Priority_nb: 2,
              Type1SourceTable_tx: 'propertytype',
              Type2_id: 8,
              Type2_tx: 'Office - Sub',
              Type2Full_tx: 'Office - Sub',
              Type2Order_nb: 2,
              Type2Priority_nb: 5,
              Type2SourceTable_tx: 'propertysubtype',
              Type3_id: 26,
              Type3_tx: 'Medical',
              Type3Full_tx: 'Medical',
              Type3Order_nb: 2,
              Type3Priority_nb: 1,
              Type3SourceTable_tx: 'feature',
              SyntheticId_tx: '6|propertytype|8|propertysubtype|26|feature',
            },
            id: '108',
            label: 'Medical',
            slug: 'medical-108',
          },
          {
            parentId: '107',
            __raw_property_type__: {
              PTSMenu_id: 109,
              Type1_id: 6,
              Type1_tx: 'Office',
              Type1Full_tx: 'Office',
              Type1Abbreviated_tx: 'Office',
              Type1_cd: 'OFF',
              Type1Order_nb: 1,
              Type1Priority_nb: 2,
              Type1SourceTable_tx: 'propertytype',
              Type2_id: 8,
              Type2_tx: 'Office - Sub',
              Type2Full_tx: 'Office - Sub',
              Type2Order_nb: 2,
              Type2Priority_nb: 5,
              Type2SourceTable_tx: 'propertysubtype',
              Type3_id: 37,
              Type3_tx: 'Park',
              Type3Full_tx: 'Park',
              Type3Order_nb: 5,
              Type3Priority_nb: 1,
              Type3SourceTable_tx: 'feature',
              SyntheticId_tx: '6|propertytype|8|propertysubtype|37|feature',
            },
            id: '109',
            label: 'Park',
            slug: 'park-109',
          },
          {
            parentId: '107',
            __raw_property_type__: {
              PTSMenu_id: 110,
              Type1_id: 6,
              Type1_tx: 'Office',
              Type1Full_tx: 'Office',
              Type1Abbreviated_tx: 'Office',
              Type1_cd: 'OFF',
              Type1Order_nb: 1,
              Type1Priority_nb: 2,
              Type1SourceTable_tx: 'propertytype',
              Type2_id: 8,
              Type2_tx: 'Office - Sub',
              Type2Full_tx: 'Office - Sub',
              Type2Order_nb: 2,
              Type2Priority_nb: 5,
              Type2SourceTable_tx: 'propertysubtype',
              Type3_id: 40,
              Type3_tx: 'R&D',
              Type3Full_tx: 'R&D',
              Type3Order_nb: 3,
              Type3Priority_nb: 1,
              Type3SourceTable_tx: 'feature',
              SyntheticId_tx: '6|propertytype|8|propertysubtype|40|feature',
            },
            id: '110',
            label: 'R&D',
            slug: 'r-d-110',
          },
          {
            parentId: '107',
            __raw_property_type__: {
              PTSMenu_id: 112,
              Type1_id: 6,
              Type1_tx: 'Office',
              Type1Full_tx: 'Office',
              Type1Abbreviated_tx: 'Office',
              Type1_cd: 'OFF',
              Type1Order_nb: 1,
              Type1Priority_nb: 2,
              Type1SourceTable_tx: 'propertytype',
              Type2_id: 8,
              Type2_tx: 'Office - Sub',
              Type2Full_tx: 'Office - Sub',
              Type2Order_nb: 2,
              Type2Priority_nb: 5,
              Type2SourceTable_tx: 'propertysubtype',
              Type3_id: 51,
              Type3_tx: 'Tech/Telecom/Data Center',
              Type3Full_tx: 'Tech/Telecom/Data',
              Type3Order_nb: 4,
              Type3Priority_nb: 1,
              Type3SourceTable_tx: 'feature',
              SyntheticId_tx: '6|propertytype|8|propertysubtype|51|feature',
            },
            id: '112',
            label: 'Tech/Telecom/Data',
            slug: 'tech-telecom-data-112',
          },
        ],
      },
    ],
    featureTypes: [
      {
        parentId: '96',
        __raw_property_type__: {
          PTSMenu_id: 97,
          Type1_id: 6,
          Type1_tx: 'Office',
          Type1Full_tx: 'Office',
          Type1Abbreviated_tx: 'Office',
          Type1_cd: 'OFF',
          Type1Order_nb: 1,
          Type1Priority_nb: 2,
          Type1SourceTable_tx: 'propertytype',
          Type2_id: null,
          Type2_tx: null,
          Type2Full_tx: null,
          Type2Order_nb: null,
          Type2Priority_nb: 6,
          Type2SourceTable_tx: null,
          Type3_id: 26,
          Type3_tx: 'Medical',
          Type3Full_tx: 'Medical',
          Type3Order_nb: 2,
          Type3Priority_nb: 1,
          Type3SourceTable_tx: 'feature',
          SyntheticId_tx: '6|propertytype|||26|feature',
        },
        id: '97',
        label: 'Medical',
        slug: 'medical-97',
      },
      {
        parentId: '96',
        __raw_property_type__: {
          PTSMenu_id: 98,
          Type1_id: 6,
          Type1_tx: 'Office',
          Type1Full_tx: 'Office',
          Type1Abbreviated_tx: 'Office',
          Type1_cd: 'OFF',
          Type1Order_nb: 1,
          Type1Priority_nb: 2,
          Type1SourceTable_tx: 'propertytype',
          Type2_id: null,
          Type2_tx: null,
          Type2Full_tx: null,
          Type2Order_nb: null,
          Type2Priority_nb: 6,
          Type2SourceTable_tx: null,
          Type3_id: 37,
          Type3_tx: 'Park',
          Type3Full_tx: 'Park',
          Type3Order_nb: 5,
          Type3Priority_nb: 1,
          Type3SourceTable_tx: 'feature',
          SyntheticId_tx: '6|propertytype|||37|feature',
        },
        id: '98',
        label: 'Park',
        slug: 'park-98',
      },
      {
        parentId: '96',
        __raw_property_type__: {
          PTSMenu_id: 99,
          Type1_id: 6,
          Type1_tx: 'Office',
          Type1Full_tx: 'Office',
          Type1Abbreviated_tx: 'Office',
          Type1_cd: 'OFF',
          Type1Order_nb: 1,
          Type1Priority_nb: 2,
          Type1SourceTable_tx: 'propertytype',
          Type2_id: null,
          Type2_tx: null,
          Type2Full_tx: null,
          Type2Order_nb: null,
          Type2Priority_nb: 6,
          Type2SourceTable_tx: null,
          Type3_id: 40,
          Type3_tx: 'R&D',
          Type3Full_tx: 'R&D',
          Type3Order_nb: 3,
          Type3Priority_nb: 1,
          Type3SourceTable_tx: 'feature',
          SyntheticId_tx: '6|propertytype|||40|feature',
        },
        id: '99',
        label: 'R&D',
        slug: 'r-d-99',
      },
      {
        parentId: '96',
        __raw_property_type__: {
          PTSMenu_id: 101,
          Type1_id: 6,
          Type1_tx: 'Office',
          Type1Full_tx: 'Office',
          Type1Abbreviated_tx: 'Office',
          Type1_cd: 'OFF',
          Type1Order_nb: 1,
          Type1Priority_nb: 2,
          Type1SourceTable_tx: 'propertytype',
          Type2_id: null,
          Type2_tx: null,
          Type2Full_tx: null,
          Type2Order_nb: null,
          Type2Priority_nb: 6,
          Type2SourceTable_tx: null,
          Type3_id: 51,
          Type3_tx: 'Tech/Telecom/Data Center',
          Type3Full_tx: 'Tech/Telecom/Data',
          Type3Order_nb: 4,
          Type3Priority_nb: 1,
          Type3SourceTable_tx: 'feature',
          SyntheticId_tx: '6|propertytype|||51|feature',
        },
        id: '101',
        label: 'Tech/Telecom/Data',
        slug: 'tech-telecom-data-101',
      },
    ],
  },
];
