import { createPropertyMenu } from './index';

const rawPropertyTypes = [
  {
    "TrendtrackerData_PropertyTypes_id": 1,
    "box3Value": "ALL",
    "box3": "All Property Types",
    "display_fg": true,
    "indent": 0,
    "propertyType_id": 0,
    "propertySubType_id": null,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Office, Industrial, Retail, Apartment, Hotel and Dev Site properties",
    "sortOrder": 1,
    "hotelRating_id": null,
    "propertyType_tx": "All Property Types"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 2,
    "box3Value": "COM",
    "box3": "Commercial",
    "display_fg": true,
    "indent": 0,
    "propertyType_id": -1,
    "propertySubType_id": null,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Office, Industrial, Retail",
    "sortOrder": 2,
    "hotelRating_id": null,
    "propertyType_tx": "Commercial"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 3,
    "box3Value": "OFF",
    "box3": "Office",
    "display_fg": true,
    "indent": 0,
    "propertyType_id": 6,
    "propertySubType_id": null,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Office",
    "sortOrder": 3,
    "hotelRating_id": null,
    "propertyType_tx": "Office"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 4,
    "box3Value": "CBD",
    "box3": "Office-CBD",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 6,
    "propertySubType_id": 7,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Central Business District",
    "sortOrder": 4,
    "hotelRating_id": null,
    "propertyType_tx": "Office"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 5,
    "box3Value": "SUB",
    "box3": "Office-Sub",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 6,
    "propertySubType_id": 8,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Suburban Office",
    "sortOrder": 5,
    "hotelRating_id": null,
    "propertyType_tx": "Office"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 6,
    "box3Value": "MED",
    "box3": "Medical",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 6,
    "propertySubType_id": null,
    "propertyFeature_id": 26,
    "PropertySubTypeCategory_id": 30,
    "definition": "Medical Office Building",
    "sortOrder": 6,
    "hotelRating_id": null,
    "propertyType_tx": "Office"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 7,
    "box3Value": "OST",
    "box3": "Single Tenant Office",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 6,
    "propertySubType_id": null,
    "propertyFeature_id": -1,
    "PropertySubTypeCategory_id": null,
    "definition": "Single Tenant Office",
    "sortOrder": 7,
    "hotelRating_id": null,
    "propertyType_tx": "Office"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 8,
    "box3Value": "IND",
    "box3": "Industrial",
    "display_fg": true,
    "indent": 0,
    "propertyType_id": 4,
    "propertySubType_id": null,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Industrial",
    "sortOrder": 8,
    "hotelRating_id": null,
    "propertyType_tx": "Industrial"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 9,
    "box3Value": "WAR",
    "box3": "Warehouse",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 4,
    "propertySubType_id": 6,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Warehouse",
    "sortOrder": 9,
    "hotelRating_id": null,
    "propertyType_tx": "Industrial"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 10,
    "box3Value": "FLX",
    "box3": "Flex",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 4,
    "propertySubType_id": 5,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Flex Industrial",
    "sortOrder": 10,
    "hotelRating_id": null,
    "propertyType_tx": "Industrial"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 11,
    "box3Value": "IST",
    "box3": "Single Tenant Industrial",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 4,
    "propertySubType_id": null,
    "propertyFeature_id": -1,
    "PropertySubTypeCategory_id": null,
    "definition": "Single Tenant Industrial",
    "sortOrder": 11,
    "hotelRating_id": null,
    "propertyType_tx": "Industrial"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 12,
    "box3Value": "RET",
    "box3": "Retail",
    "display_fg": true,
    "indent": 0,
    "propertyType_id": 7,
    "propertySubType_id": null,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Retail",
    "sortOrder": 12,
    "hotelRating_id": null,
    "propertyType_tx": "Retail"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 13,
    "box3Value": "STR",
    "box3": "Centers",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 7,
    "propertySubType_id": 9,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Centers",
    "sortOrder": 13,
    "hotelRating_id": null,
    "propertyType_tx": "Retail"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 14,
    "box3Value": "MAL",
    "box3": "Shops",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 7,
    "propertySubType_id": 10,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Shops",
    "sortOrder": 17,
    "hotelRating_id": null,
    "propertyType_tx": "Retail"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 15,
    "box3Value": "RAC",
    "box3": "Anchored Center",
    "display_fg": true,
    "indent": 2,
    "propertyType_id": 7,
    "propertySubType_id": 9,
    "propertyFeature_id": 2,
    "PropertySubTypeCategory_id": 2,
    "definition": "Anchored Center",
    "sortOrder": 14,
    "hotelRating_id": null,
    "propertyType_tx": "Retail"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 16,
    "box3Value": "RUC",
    "box3": "Unanchored Center",
    "display_fg": true,
    "indent": 2,
    "propertyType_id": 7,
    "propertySubType_id": 9,
    "propertyFeature_id": 54,
    "PropertySubTypeCategory_id": 62,
    "definition": "Unanchored Center",
    "sortOrder": 16,
    "hotelRating_id": null,
    "propertyType_tx": "Retail"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 17,
    "box3Value": "RST",
    "box3": "Single Tenant Retail",
    "display_fg": true,
    "indent": 2,
    "propertyType_id": 7,
    "propertySubType_id": null,
    "propertyFeature_id": -1,
    "PropertySubTypeCategory_id": null,
    "definition": "Single Tenant Retail",
    "sortOrder": 18,
    "hotelRating_id": null,
    "propertyType_tx": "Retail"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 18,
    "box3Value": "APT",
    "box3": "Apartment",
    "display_fg": true,
    "indent": 0,
    "propertyType_id": 1,
    "propertySubType_id": null,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Apartment",
    "sortOrder": 27,
    "hotelRating_id": null,
    "propertyType_tx": "Apartment"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 19,
    "box3Value": "GAR",
    "box3": "Garden",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 1,
    "propertySubType_id": 2,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Garden Apartment",
    "sortOrder": 28,
    "hotelRating_id": null,
    "propertyType_tx": "Apartment"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 20,
    "box3Value": "MID",
    "box3": "Mid/Highrise",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 1,
    "propertySubType_id": 1,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Mid/Highrise Apartment",
    "sortOrder": 29,
    "hotelRating_id": null,
    "propertyType_tx": "Apartment"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 21,
    "box3Value": "STU",
    "box3": "Student Housing",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 1,
    "propertySubType_id": null,
    "propertyFeature_id": 49,
    "PropertySubTypeCategory_id": 57,
    "definition": "Student Housing",
    "sortOrder": 30,
    "hotelRating_id": null,
    "propertyType_tx": "Apartment"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 22,
    "box3Value": "HTL",
    "box3": "Hotel",
    "display_fg": true,
    "indent": 0,
    "propertyType_id": 3,
    "propertySubType_id": null,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Hotel",
    "sortOrder": 21,
    "hotelRating_id": null,
    "propertyType_tx": "Hotel"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 23,
    "box3Value": "LIM",
    "box3": "Limited-Service",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 3,
    "propertySubType_id": 4,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Limited-Service Hotel",
    "sortOrder": 22,
    "hotelRating_id": null,
    "propertyType_tx": "Hotel"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 24,
    "box3Value": "FUL",
    "box3": "Full-Service",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 3,
    "propertySubType_id": 3,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Full-Service Hotel",
    "sortOrder": 23,
    "hotelRating_id": null,
    "propertyType_tx": "Hotel"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 25,
    "box3Value": "SHC",
    "box3": "Seniors Housing & Care",
    "display_fg": true,
    "indent": 0,
    "propertyType_id": 11,
    "propertySubType_id": null,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Seniors Housing & Care",
    "sortOrder": 31,
    "hotelRating_id": null,
    "propertyType_tx": "Seniors Housing & Care"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 26,
    "box3Value": "NUR",
    "box3": "Nursing Care",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 11,
    "propertySubType_id": 57,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Nursing Care",
    "sortOrder": 32,
    "hotelRating_id": null,
    "propertyType_tx": "Seniors Housing & Care"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 27,
    "box3Value": "SEN",
    "box3": "Seniors Housing",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 11,
    "propertySubType_id": 56,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Seniors Housing",
    "sortOrder": 33,
    "hotelRating_id": null,
    "propertyType_tx": "Seniors Housing & Care"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 28,
    "box3Value": "DEV",
    "box3": "Dev Site",
    "display_fg": true,
    "indent": 0,
    "propertyType_id": 8,
    "propertySubType_id": null,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Dev Site",
    "sortOrder": 37,
    "hotelRating_id": null,
    "propertyType_tx": "Dev Site"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 29,
    "box3Value": "GAC",
    "box3": "Grocery Anchored Center",
    "display_fg": true,
    "indent": 2,
    "propertyType_id": 7,
    "propertySubType_id": 9,
    "propertyFeature_id": 18,
    "PropertySubTypeCategory_id": null,
    "definition": "Grocery Anchored Center",
    "sortOrder": 15,
    "hotelRating_id": null,
    "propertyType_tx": "Retail"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 30,
    "box3Value": "DRG",
    "box3": "Drug Stores",
    "display_fg": true,
    "indent": 2,
    "propertyType_id": 7,
    "propertySubType_id": 10,
    "propertyFeature_id": 12,
    "PropertySubTypeCategory_id": null,
    "definition": "Drug Stores",
    "sortOrder": 19,
    "hotelRating_id": null,
    "propertyType_tx": "Retail"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 31,
    "box3Value": "USF",
    "box3": "Urban/Storefront",
    "display_fg": true,
    "indent": 2,
    "propertyType_id": 7,
    "propertySubType_id": 10,
    "propertyFeature_id": 55,
    "PropertySubTypeCategory_id": null,
    "definition": "Urban/Storefront",
    "sortOrder": 20,
    "hotelRating_id": null,
    "propertyType_tx": "Retail"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 32,
    "box3Value": "HEC",
    "box3": "Economy",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 3,
    "propertySubType_id": null,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Economy",
    "sortOrder": 24,
    "hotelRating_id": 1,
    "propertyType_tx": "Hotel"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 33,
    "box3Value": "HMS",
    "box3": "Midscale",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 3,
    "propertySubType_id": null,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Midscale",
    "sortOrder": 25,
    "hotelRating_id": 3,
    "propertyType_tx": "Hotel"
  },
  {
    "TrendtrackerData_PropertyTypes_id": 34,
    "box3Value": "HUS",
    "box3": "Upscale",
    "display_fg": true,
    "indent": 1,
    "propertyType_id": 3,
    "propertySubType_id": null,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Upscale",
    "sortOrder": 26,
    "hotelRating_id": 2,
    "propertyType_tx": "Hotel"
  }
]
const propertyTypeWithNoChildren = {
  "TrendtrackerData_PropertyTypes_id": 1,
  "box3Value": "ALL",
  "box3": "All Property Types",
  "display_fg": true,
  "indent": 0,
  "propertyType_id": 0,
  "propertySubType_id": null,
  "propertyFeature_id": null,
  "PropertySubTypeCategory_id": null,
  "definition": "Office, Industrial, Retail, Apartment, Hotel and Dev Site properties",
  "sortOrder": 1,
  "hotelRating_id": null,
  "propertyType_tx": "All Property Types",
  "label": "All Property Types",
  "id": "0",
  "value": "0",
  "options": []
};
const propertyTypeWithChildren = {
    "TrendtrackerData_PropertyTypes_id": 3,
    "box3Value": "OFF",
    "box3": "Office",
    "display_fg": true,
    "indent": 0,
    "propertyType_id": 6,
    "propertySubType_id": null,
    "propertyFeature_id": null,
    "PropertySubTypeCategory_id": null,
    "definition": "Office",
    "sortOrder": 3,
    "hotelRating_id": null,
    "propertyType_tx": "Office",
    "label": "Office",
    "id": "6",
    "value": "6",
    "options": [
      {
        "TrendtrackerData_PropertyTypes_id": 4,
        "box3Value": "CBD",
        "box3": "Office-CBD",
        "display_fg": true,
        "indent": 1,
        "propertyType_id": 6,
        "propertySubType_id": 7,
        "propertyFeature_id": null,
        "PropertySubTypeCategory_id": null,
        "definition": "Central Business District",
        "sortOrder": 4,
        "hotelRating_id": null,
        "propertyType_tx": "Office",
        "label": "Office-CBD",
        "id": "6-7",
        "value": "7"
      },
      {
        "TrendtrackerData_PropertyTypes_id": 5,
        "box3Value": "SUB",
        "box3": "Office-Sub",
        "display_fg": true,
        "indent": 1,
        "propertyType_id": 6,
        "propertySubType_id": 8,
        "propertyFeature_id": null,
        "PropertySubTypeCategory_id": null,
        "definition": "Suburban Office",
        "sortOrder": 5,
        "hotelRating_id": null,
        "propertyType_tx": "Office",
        "label": "Office-Sub",
        "id": "6-8",
        "value": "8"
      }
    ]
  };

  describe('propertyMenuBuilder', () => {

  test('propertyBuilder', () => {
    const createPropertyMenuResult = createPropertyMenu(rawPropertyTypes);
    expect(createPropertyMenuResult[0]).toStrictEqual(propertyTypeWithNoChildren);
    expect(createPropertyMenuResult[2]).toStrictEqual(propertyTypeWithChildren);
  });

});