version: '2'
services:
  cd-product-api:
    image: $TAG2
    environment:
      API_HOST: ${config.apiHost}
      API_PORT: ${config.apiPort}
      COGNITO_CLIENT_ID: ${config.cognitoClientId}
      COGNITO_REGION: ${config.cognitoRegion}
      COGNITO_USER_POOL_ID: ${config.UserPoolId}
      DB_RCA_WEB_CONNECTION_TIMEOUT: ${config.dbRcaConnectionTimeout}
      DB_RCA_WEB_DATABSE: ${config.dbRcaWebDatabase}
      DB_RCA_WEB_PASSWORD: ${config.dbRcaWebPassword}
      DB_RCA_WEB_POOL_IDLE_TIMEOUT_MS: ${config.dbRcaWebPoolIdleTimeoutMs}
      DB_RCA_WEB_POOL_MAX: ${config.dbRcaWebPoolMax}
      DB_RCA_WEB_POOL_MIN: ${config.dbRcaWebPoolMin}
      DB_RCA_WEB_SERVER: ${config.dbRcaWebServer}
      DB_RCA_WEB_USER: ${config.dbRcaWebUser}
    stdin_open: true
    tty: true
    logging:
      driver: syslog
      options:
        syslog-address: tcp://0.0.0.0:5001
        tag: ${config.serviceName}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
      type: ${config.serviceName}