version: '2'
services:
  cd-product-api:
    image: ${params.image}
    environment:
      API_HOST: ${config.apiHost}
      API_PORT: ${config.apiPort}
      COGNITO_CLIENT_ID: ${config.cognitoClientId}
      COGNITO_REGION: ${config.cognitoRegion}
      COGNITO_USER_POOL_ID: ${config.cognitoUserPoolId}
      DB_RCA_WEB_CONNECTION_TIMEOUT: ${config.sqlDbConnectionTimeout}
      DB_RCA_WEB_DATABSE: ${config.sqlDb}
      DB_RCA_WEB_PASSWORD: ${config.sqlPassword}
      DB_RCA_WEB_POOL_IDLE_TIMEOUT_MS: ${config.sqlDbPoolIdleTimeoutMs}
      DB_RCA_WEB_POOL_MAX: ${config.sqlDbPoolMax}
      DB_RCA_WEB_POOL_MIN: ${config.sqlDbPoolMin}
      DB_RCA_WEB_SERVER: ${config.sqlServer}
      DB_RCA_WEB_USER: ${config.sqlUser}
    stdin_open: true
    tty: true
    logging:
      driver: syslog
      options:
        syslog-address: tcp://0.0.0.0:5001
        tag: ${config.serviceName}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
      type: ${config.serviceName}