version: '3'

services:
  virtual-cognito:
    image: rcanalytics/product-api-virtual-cognito:latest
    ports:
      - 10203:10203

  mssql:
    image: rcanalytics/product-api-mssql-rca-web-accounts:latest
    ports:
      - 1433:1433

  elasticsearch:
    image: rcanalytics/product-api-elasticsearch-transactions:latest
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  redis:
    image: redis
    ports:
      - 6379:6379
