version: '3'

services:
  mssql:
    build: ./mssql-rca-web-accounts/
    image: rcanalytics/product-api-mssql-rca-web-accounts:latest
    ports:
      - 1433:1433

  elasticsearch:
    build: ./elasticsearch-transactions/
    image: rcanalytics/product-api-elasticsearch-transactions:latest
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  redis:
    image: redis
    ports:
      - 6379:6379
