version: '3'

services:
  mssql:
    build: ./db/
    image: product-api-sql
    ports:
      - 1433:1433
  
  elasticsearch:
    image: elasticsearch:7.9.3 
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  redis:
    image: redis
    ports:
      - 6379:6379