kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: cd-product-api
  name: cd-product-api
  namespace: cd-{{ .Values.environment }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: cd-product-api
  template:
    metadata:
      labels:
        k8s-app: cd-product-api
    spec:
      containers:
        - name: cd-product-api
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: 8080
      imagePullSecrets:
        - name: dockerhub
      serviceAccountName: cd-product-api
      nodeSelector:
        kubernetes.io/os: linux