kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: cd-{{ .Values.environment }}-product-api
  name: cd-{{ .Values.environment }}-product-api
  namespace: cd
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: cd-{{ .Values.environment }}-product-api
  template:
    metadata:
      labels:
        k8s-app: cd-{{ .Values.environment }}-product-api
    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
            - name: ELASTICSEARCH_USERNAME
              value: "{{ .Values.esUsername }}"
            - name: ELASTICSEARCH_PASSWORD
              value: "{{ .Values.esPassword }}"
            - name: ELASTICSEARCH_NODE
              value: "{{ .Values.esUrl }}"
            - name: MSSQL_URI
              value: "{{ .Values.rcaWebAccountsUri }}"
            - name: LAUNCH_DARKLY_SDK
              value: "{{ .Values.launchDarklySdk }}"
            - name: SEGMENT_ACCESS_KEY
              value: "{{ .Values.segmentAccessKey }}"
            - name: COGNITO_REGION
              value: "{{ .Values.cognitoRegion }}"
            - name: COGNITO_USER_POOL_ID
              value: "{{ .Values.cognitoUserPoolId }}"
            - name: COGNITO_APP_CLIENT_ID
              value: "{{ .Values.cognitoAppClientId }}"
            - name: COGNITO_APP_CLIENT_SECRET
              value: "{{ .Values.cognitoAppClientSecret }}"
            - name: REDIS_URI
              value: "redis://cd-{{ .Values.environment }}-product-api-redis.cd:6379"
            - name: TRANSACTIONS_INDEX
              value: "{{ .Values.environment }}7_multi_pst"
        - name: redis
          image: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
      imagePullSecrets:
        - name: dockerhub
      serviceAccountName: cd-{{ .Values.environment }}-product-api
      nodeSelector:
        kubernetes.io/os: linux
