apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    k8s-app: cd-product-api
  name: cd-product-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cd-product-api
subjects:
  - kind: ServiceAccount
    name: cd-product-api

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cd-product-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cd-product-api
subjects:
  - kind: ServiceAccount
    name: cd-product-api