const {
	API_HOST,
	API_PORT,
	COGNITO_CLIENT_ID,
	COGNITO_REGION,
	COGNITO_USER_POOL_ID,
	DB_RCA_WEB_CONNECTION_TIMEOUT,
	DB_RCA_WEB_DATABSE,
	DB_RCA_WEB_PASSWORD,
	DB_RCA_WEB_POOL_IDLE_TIMEOUT_MS,
	DB_RCA_WEB_POOL_MAX,
	DB_RCA_WEB_POOL_MIN,
	DB_RCA_WEB_SERVER,
	DB_RCA_WEB_USER,
} = process.env;

const safeInt = (v: string) =>
	typeof v !== 'undefined' ? parseInt(v, 10) : null;

const env = {
	API_HOST,
	API_PORT,
	COGNITO_CLIENT_ID,
	COGNITO_REGION,
	COGNITO_USER_POOL_ID,
	DB_RCA_WEB_CONNECTION_TIMEOUT: safeInt(DB_RCA_WEB_CONNECTION_TIMEOUT),
	DB_RCA_WEB_DATABSE,
	DB_RCA_WEB_PASSWORD,
	DB_RCA_WEB_POOL_IDLE_TIMEOUT_MS: safeInt(DB_RCA_WEB_POOL_IDLE_TIMEOUT_MS),
	DB_RCA_WEB_POOL_MAX: safeInt(DB_RCA_WEB_POOL_MAX),
	DB_RCA_WEB_POOL_MIN: safeInt(DB_RCA_WEB_POOL_MIN),
	DB_RCA_WEB_SERVER,
	DB_RCA_WEB_USER,
};

export default env;
