name: Prepare Deploy

on: repository_dispatch

jobs:
  prepare_deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Dispatch Event
        run: echo "${{ toJSON(github.event) }}"

      - name: Checkout Current Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}

      - name: Checkout Actions Repo
        uses: actions/checkout@v2
        with:
          repository: rcanalytics/github-actions
          ref: v1
          path: .github-actions
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Checkout Workflow Config
        uses: ./.github-actions/repo/checkout
        with:
          repository: rcanalytics/workflow-config
          path: .workflow-config
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup Workflow Config
        uses: ./.github-actions/workflow/gen-config
        with:
          vaultToken: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set Environment From Payload
        if: github.event.client_payload.environment != null
        uses: ./.github-actions/git-env
        with:
          gitRef: ${{ github.event.client_payload.branch }}
          gitEnv: ${{ github.event.client_payload.environment }}

      - name: Set Environment From Branch
        if: github.event.client_payload.environment == null
        uses: ./.github-actions/git-env
        with:
          gitRef: ${{ github.event.client_payload.branch }}
          gitMap: |
            master:test
            hotfix/*:dev
            develop:dev
            feature/*:dev
            
      - name: Set Image Env From Payload
        if: github.event.client_payload.image != null
        run: echo "::set-env name=IMAGE_NAME::${{ github.event.client_payload.image }}"

      - name: Set Image Env From Latest Deployed
        if: github.event.client_payload.image == null
        uses: ./.github-actions/repo/image
        with:
          branch: ${{ github.event.client_payload.branch }}

      - name: Start Deployment
        uses: ./.github-actions/repo/deploy
        with:
          branch: ${{ github.event.client_payload.branch }}
          environment: ${{ env.ENV_NAME }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
          payload: |
            image:${{ env.IMAGE_NAME }}